import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
const {openMarketAlertsStore}=await import('./market-alerts-store.ts');
const {marketBriefReportFingerprint}=await import('./market-alert-brief-store.ts');
const dir=mkdtempSync(join(tmpdir(),'market-brief-'));
const path=join(dir,'alerts.sqlite');
let store=openMarketAlertsStore(path);
const now=Date.parse('2026-09-18T02:00:00Z');
const minute=60000;
function event(id,symbol,ago,side='LONG',type='volatility') {
  return {id,symbol,type,side,level:1,stage:'test',trigger:'test',source:'ws',price:1,changePct:5,volumeRatio:3,score:null,metrics:{},reasons:[],occurredAt:new Date(now-ago).toISOString()};
}
function enrich(symbol, patch={}, age=0, extra={}) {
  const at=new Date(now-age).toISOString();
  const metrics={symbol,observedAt:at,stale:false,pct1m:.3,pct5m:2,pct15m:4,pct1h:5,pct24h:10,volumeRatio1m:2,volumeRatio5m:2,oiGrowth15m:3,oiNotional:10000000,funding:0,basis:0,globalLongShortRatio:1,topTraderLongShortRatio:1,takerBuySellRatio:1.2,spotAvailable:false,spotChange15m:null,spotVolumeRatio5m:null,perpSpotDivergencePct:null,distanceFromHighPct:1,distanceFromLowPct:5,priorRunUpPct:10,supportBreak:false,lowerStructure:false,breakout20:true,quoteVolume:10000000,marketCapUsd:null,fdvUsd:null,alertCounts:{pump:1,crash:0,squeeze:0,total:1},...patch};
  store.upsertOpportunityEnrichment({symbol,metrics,fetchedAt:at,stale:false,error:null,...extra});
}
try {
  for(let i=0;i<250;i++) store.insertMarketAlertEvent(event(`old${i}`,'OLDUSDT',120*minute+i));
  store.insertMarketAlertEvent(event('fresh','FRESHUSDT',2*minute)); enrich('FRESHUSDT');
  store.insertMarketAlertEvent(event('fade','FADEUSDT',5*minute)); enrich('FADEUSDT',{pct5m:.2,volumeRatio5m:1.1,breakout20:false});
  store.insertMarketAlertEvent(event('stale','STALEUSDT',minute)); enrich('STALEUSDT',{},21*minute);
  store.insertMarketAlertEvent(event('missing','MISSINGUSDT',minute));
  store.insertMarketAlertEvent(event('reverse','REVERSEUSDT',minute)); enrich('REVERSEUSDT',{pct5m:-2,pct15m:-3});
  store.insertMarketAlertEvent(event('boundary','BOUNDARYUSDT',180*minute));
  store.insertMarketAlertEvent(event('future','FUTUREUSDT',-minute));
  const input=store.getMarketBriefInput(now);
  assert.equal(input['3h'].totals.total,255,'aggregate full window, not paginated feed');
  assert.equal(input['24h'].totals.total,256,'strict window boundary; future event excluded');
  assert.deepEqual(input['3h'].items.map(x=>x.symbol),['FRESHUSDT','FADEUSDT'],'fresh confirmed data outranks alert spam; stale/missing/reversed excluded');
  assert.equal(input['24h'].items[0].symbol,'OLDUSDT','historical frequency retained in retrospective');
  assert.equal(input['3h'].items[0].tracking.state,'new');
  assert.equal(input['3h'].items[1].tracking.state,'waiting');
  assert.equal(input['3h'].items[0].tracking.evidence.length,2);
  assert.match(input['3h'].items[0].tracking.evidence.join(' '),/2\.00/);
  assert.match(input['3h'].items[0].tracking.nextWatch,/5.*15/);
  assert.ok(input['3h'].items[0].tracking.dropIf);
  assert.deepEqual(input['3h'].changes.added,['FRESHUSDT','FADEUSDT']);
  assert.equal(store.claimMarketBriefCheck(now),true);
  store.saveMarketBriefCache(input,'first',now);
  enrich('FRESHUSDT',{},-5*minute);
  const steady=store.getMarketBriefInput(now+5*minute)['3h'];
  assert.equal(steady.items[0].tracking.state,'continuing','fresh unchanged evidence is sustained, not strengthened or downgraded');
  assert.deepEqual(steady.changes.downgraded,[]);
  assert.equal(store.claimMarketBriefCheck(now+9*minute),false);
  store.close(); store=openMarketAlertsStore(path);
  assert.equal(store.claimMarketBriefCheck(now+9*minute),false,'restart preserves cooldown');
  assert.equal(store.claimMarketBriefCheck(now+10*minute),true);
  enrich('FRESHUSDT',{volumeRatio5m:3,pct5m:3},-10*minute);
  enrich('FADEUSDT',{pct5m:-2,pct15m:-4},-10*minute);
  const next=store.getMarketBriefInput(now+10*minute);
  assert.equal(next['3h'].items[0].tracking.state,'strengthening');
  assert.deepEqual(next['3h'].changes.added,[]);
  assert.deepEqual(next['3h'].changes.downgraded,['FADEUSDT']);
  store.saveMarketBriefCache(next,'next',now+10*minute,true);
  assert.equal(store.saveMarketBriefCache(input,'late',now),false,'late AI result cannot overwrite a newer claimed cycle');
  assert.equal(store.readMarketBriefCache(now+10*minute).reports['3h'].stale,false,'AI outage does not stale fresh rule evidence');
  assert.equal(store.readMarketBriefCache(now+40*minute).reports['3h'].stale,true);
  const empty=store.getMarketBriefInput(now+40*minute);
  assert.equal(empty['3h'].items.length,0,'all expired evidence may produce empty list');
  assert.equal(empty['3h'].status,'empty');
  store.close();
  const db=new DatabaseSync(path);
  const legacy={'3h':{...input['3h'],schemaVersion:undefined},'24h':{...input['24h'],schemaVersion:undefined}};
  db.prepare('UPDATE market_alert_brief SET schema_version=1,next_check_ms=?, checked_at=?,reports_json=? WHERE id=1').run(now+180*minute,new Date(now).toISOString(),JSON.stringify(legacy));db.close();
  store=openMarketAlertsStore(path);
  assert.equal(store.readMarketBriefCache(now).reports['3h'],undefined,'legacy counts never presented as tracking');
  assert.equal(store.claimMarketBriefCheck(now+minute),true,'upgrade allows immediate check');
  store.saveMarketBriefCache(input,'migrated',now+minute);
  assert.equal(store.claimMarketBriefCheck(now+2*minute),false,'migration is once even on reopen');
  for (const symbol of ['B1','B2','B3','B4']) {store.insertMarketAlertEvent(event(symbol,symbol,minute));enrich(symbol);}
  assert.equal(store.getMarketBriefInput(now)['3h'].items.length,3,'selection hard maximum');
  enrich('FRESHUSDT',{observedAt:new Date(now+minute).toISOString()});
  enrich('B1',{volumeRatio5m:null});enrich('B2',{},0,{error:'fetch failed'});enrich('B3',{},0,{stale:true});
  assert.deepEqual(store.getMarketBriefInput(now)['3h'].items.map(x=>x.symbol),['B4']);
  enrich('B4',{pct15m:.8});
  const waiting=store.getMarketBriefInput(now);
  store.saveMarketBriefCache(waiting,'waiting',now+minute);
  enrich('B4',{pct15m:1.2},-2*minute);
  const confirmed=store.getMarketBriefInput(now+2*minute);
  assert.equal(confirmed['3h'].items.find(item=>item.symbol==='B4').tracking.state,'strengthening','crossing slower confirmation threshold changes status');
  assert.notEqual(marketBriefReportFingerprint(waiting['3h']),marketBriefReportFingerprint(confirmed['3h']));
  store.close();store=openMarketAlertsStore(join(dir,'directions.sqlite'));
  store.insertMarketAlertEvent(event('short','DOWNUSDT',minute,'SHORT'));
  enrich('DOWNUSDT',{pct5m:-2,pct15m:-4});
  store.insertMarketAlertEvent(event('squeeze','SQUSDT',minute,null,'short_squeeze'));
  enrich('SQUSDT',{pct1m:.2,pct5m:.8,pct15m:100,volumeRatio1m:1.1,volumeRatio5m:50});
  const directions=store.getMarketBriefInput(now)['3h'];
  assert.equal(directions.items.find(x=>x.symbol==='DOWNUSDT').direction,'down');
  const squeeze=directions.items.find(x=>x.symbol==='SQUSDT').tracking;
  assert.equal(squeeze.state,'waiting','squeeze trigger metrics must not masquerade as fresh confirmation');
  assert.match(squeeze.evidence[0],/1m \/ 5m/);
  assert.match(squeeze.evidence[1],/1\.10/);
  assert.doesNotMatch(squeeze.evidence.join(' '),/100\.00|50\.00/);
} finally {try{store.close()}catch{} rmSync(dir,{recursive:true,force:true});}
