export const MARKET_OPPORTUNITY_RULES = {
  observeScore: 70,
  actionableScore: 80,
  exitScore: 60,
  enrichmentLimit: 12,
  outputLimit: 5,
  enrichmentFreshMs: 2 * 60_000,
  confirmationFreshMs: 2 * 60 * 60_000,
  maxLifetimeMs: 12 * 60 * 60_000,
  replacementGap: 5,
  entryScans: 2,
  exitScans: 3,
  aiCooldownMs: 10 * 60_000,
  aiHourlyLimit: 6,
  diagnosticRetentionMs: 7 * 24 * 60 * 60_000,
  maxConcurrency: 3,
  capitalLong: {
    pct5m: 12,
    pct15m: 14,
    pct1h: 10,
    volume: 12,
    openInterest: 14,
    taker: 14,
    spot: 10,
    repeatedAlerts: 8,
    breakout: 8,
  },
  distributionShort: {
    priorRunUp: 20,
    highFailure: 10,
    pct5m: 8,
    pct15m: 12,
    pct1h: 8,
    volume: 8,
    taker: 14,
    lowerStructure: 12,
    supportBreak: 14,
    openInterest: 10,
    repeatedAlerts: 6,
  },
  squeezeLong: {
    fundingExtreme: 20,
    funding: 15,
    basis: 10,
    openInterestExtreme: 20,
    openInterest: 15,
    openInterestSetup: 10,
    globalCrowding: 10,
    topCrowding: 10,
    taker: 12,
    volume: 8,
    priceTrigger: 10,
    repeatedAlerts: 5,
  },
} as const;

export type MarketOpportunityRules = typeof MARKET_OPPORTUNITY_RULES;
