import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const {openMarketAlertsStore}=await import('./market-alerts-store.ts');
const worker=await import('./market-alert-brief-worker.ts').catch(()=>({}));
assert.equal(typeof worker.runMarketBriefCheck,'function','summary worker exists');
const dir=mkdtempSync(join(tmpdir(),'market-brief-worker-'));
const path=join(dir,'alerts.sqlite');
const now=Date.parse('2026-09-18T06:00:00Z');
const interval=3*3600000;
const openStore=()=>openMarketAlertsStore(path);
const seed=openStore();
seed.insertMarketAlertEvent({id:'one',symbol:'AAAUSDT',type:'volatility',side:'LONG',level:1,stage:'test',trigger:'test',source:'ws',price:1,changePct:5,volumeRatio:3,score:null,metrics:{},reasons:[],occurredAt:new Date(now-3*3600000).toISOString()});
seed.close();
let calls=0;
let fail=false;
const fetchImpl=async (_url,options)=>{
  calls++;
  const request=JSON.parse(options.body);
  assert.equal(request.model,'MiniMax-M3');
  assert.equal(request.thinking.type,'disabled');
  assert.match(request.messages[1].content,/3h或24h/);
  assert.doesNotMatch(request.messages[1].content,/1h/);
  if(fail) return new Response('{}',{status:429});
  return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({summaries:[{scope:'24h',headline:'上涨预警集中于少数币种。',items:[{symbol:'AAAUSDT',reason:'出现上涨预警，仍需观察延续。'}]}]})}}]});
};
const env={MINIMAX_API_KEY:'test',AI_SUMMARY_MODEL:'MiniMax-M3'};
try{
  const first=await worker.runMarketBriefCheck({nowMs:now,openStore,env,fetchImpl});
  assert.equal(first.status,'generated');assert.equal(calls,1);
  assert.equal((await worker.runMarketBriefCheck({nowMs:now+1000,openStore,env,fetchImpl})).status,'cooldown');
  assert.equal(calls,1);
  const restarted=await worker.runMarketBriefCheck({nowMs:now+179*60000,openStore,env,fetchImpl});
  assert.equal(restarted.nextCheckAt,now+interval,'restart waits only until persisted deadline');
  assert.equal((await worker.runMarketBriefCheck({nowMs:now+interval,openStore,env,fetchImpl})).status,'unchanged');
  assert.equal(calls,1);
  const db=openStore();
  const cached=db.readMarketBriefCache(now+interval).reports;
  assert.equal(cached['3h'].status,'empty');assert.equal(cached['24h'].model,'MiniMax-M3');
  assert.equal(cached['24h'].totals.total,1);
  assert.equal(cached['24h'].windowEnd,new Date(now+interval).toISOString());
  db.insertMarketAlertEvent({id:'two',symbol:'AAAUSDT',type:'volatility',side:'SHORT',level:2,stage:'test',trigger:'test',source:'ws',price:0.9,changePct:-5,volumeRatio:3,score:null,metrics:{},reasons:[],occurredAt:new Date(now+2*interval-1000).toISOString()});db.close();
  fail=true;
  assert.equal((await worker.runMarketBriefCheck({nowMs:now+2*interval,openStore,env,fetchImpl})).status,'error');
  assert.equal(calls,2,'no automatic retry or alternate provider');
  const after=openStore();
  const report=after.readMarketBriefCache(now+2*interval).reports['24h'];
  assert.equal(report.status,'error');assert.equal(report.stale,true);assert.equal(report.totals.total,1,'last good result retained');
  after.close();
  assert.equal((await worker.runMarketBriefCheck({nowMs:now+2*interval+1000,openStore,env,fetchImpl})).status,'cooldown');
  const db2=openStore();
  const both=db2.getMarketBriefInput(now+2*interval);db2.close();
  const valid={summaries:Object.values(both).map(report=>({scope:report.scope,headline:'预警方向有反复。',items:report.items.map(item=>({symbol:item.symbol,reason:'关注后续变化。'}))}))};
  assert.equal(worker.parseMarketBriefResponse(JSON.stringify(valid),both).length,2);
  const forged=structuredClone(valid);forged.summaries[0].items[0].symbol='FAKEUSDT';
  assert.throws(()=>worker.parseMarketBriefResponse(JSON.stringify(forged),both),/symbol/);
  const duplicated=structuredClone(valid);duplicated.summaries[1].scope='3h';
  assert.throws(()=>worker.parseMarketBriefResponse(JSON.stringify(duplicated),both),/shape/);
  const oldScope=structuredClone(valid);oldScope.summaries[0].scope='1h';
  assert.throws(()=>worker.parseMarketBriefResponse(JSON.stringify(oldScope),both),/shape/);
  let batchedCalls=0;
  const newPath=join(dir,'batch.sqlite');
  const batchStore=()=>openMarketAlertsStore(newPath);
  const batchSeed=batchStore();
  batchSeed.insertMarketAlertEvent({id:'batch',symbol:'AAAUSDT',type:'volatility',side:'LONG',level:1,stage:'test',trigger:'test',source:'ws',price:1,changePct:5,volumeRatio:3,score:null,metrics:{},reasons:[],occurredAt:new Date(now-1000).toISOString()});
  const batchInputs=batchSeed.getMarketBriefInput(now);batchSeed.close();
  const batchedFetch=async()=>{batchedCalls++;return Response.json({choices:[{message:{content:JSON.stringify({summaries:Object.values(batchInputs).map(report=>({scope:report.scope,headline:'上涨预警集中。',items:report.items.map(item=>({symbol:item.symbol,reason:'等待后续确认。'}))}))})}}]});};
  const concurrent=await Promise.all([worker.runMarketBriefCheck({nowMs:now,openStore:batchStore,env,fetchImpl:batchedFetch}),worker.runMarketBriefCheck({nowMs:now,openStore:batchStore,env,fetchImpl:batchedFetch})]);
  assert.equal(batchedCalls,1,'both windows and concurrent workers share a single call');
  assert.deepEqual(concurrent.map(r=>r.status).sort(),['cooldown','generated']);
  const emptyPath=join(dir,'empty.sqlite');
  assert.equal((await worker.runMarketBriefCheck({nowMs:now,openStore:()=>openMarketAlertsStore(emptyPath),env,fetchImpl:async()=>{throw new Error('empty window must not call AI');}})).status,'empty');
}finally{rmSync(dir,{recursive:true,force:true});}
