import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const handlers = new Map(), notices = [], navigation = [];
const self = { location: { origin: 'https://hub.example.com' }, addEventListener: (kind, fn) => handlers.set(kind, fn), skipWaiting: async () => {}, registration: { showNotification: async (title, options) => notices.push({ title, options }) }, clients: { claim: async () => {}, matchAll: async () => [{ url: 'https://hub.example.com/', navigate: async url => { navigation.push(url); }, focus: async () => navigation.push('focus') }], openWindow: async url => navigation.push(url) } };
vm.runInNewContext(readFileSync(new URL('../../public/sw.js', import.meta.url), 'utf8'), { self, URL });
let work;
handlers.get('push')({ data: { json: () => ({ title: 'Important', body: 'body', episodeId: 'shared', target: 'https://evil.test/x' }) }, waitUntil: promise => { work = promise; } }); await work;
assert.equal(notices[0].options.tag, 'signal-hub:shared'); assert.equal(notices[0].options.data.target, 'https://hub.example.com/settings');
assert.ok(readFileSync(new URL('../../public' + notices[0].options.icon, import.meta.url)).length);
assert.ok(readFileSync(new URL('../../public' + notices[0].options.badge, import.meta.url)).length);
handlers.get('notificationclick')({ notification: { data: { target: '/alerts?symbol=BTCUSDT#market-push-BTCUSDT' }, close() {} }, waitUntil: promise => { work = promise; } }); await work;
assert.deepEqual(navigation, ['https://hub.example.com/alerts?symbol=BTCUSDT#market-push-BTCUSDT', 'focus']);
handlers.get('push')({ data: { json: () => { throw new Error('invalid json'); } }, waitUntil: promise => { work = promise; } }); await work;
assert.equal(notices.length, 2); assert.equal(notices[1].title, 'Signal Hub');
assert.equal(handlers.has('fetch'), false, 'private data never cached');
self.clients.matchAll = async () => []; navigation.length = 0;
handlers.get('notificationclick')({ notification: { data: { target: '//evil.test/x' }, close() {} }, waitUntil: promise => { work = promise; } }); await work;
assert.deepEqual(navigation, ['https://hub.example.com/settings']);
console.log('service worker visible notifications and safe navigation passed');
