import assert from 'node:assert/strict';
import { createECDH, randomBytes, randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { openMarketAlertsStore } from './market-alerts-store.ts';
import { openWebPushStore } from './web-push-store.ts';
import { qualifyOpportunity } from './important-push-policy.ts';
import { createMarketPushSource, createNewsPushSource, runWebPushCycle } from './web-push-worker.ts';
import { getOrCreateDailyInvestmentBrief, readDailyBriefPushOutboxAfter } from './daily-investment-brief.ts';
import { opportunityDecision, pushNowMs, pushNow } from './important-push-test-fixtures.mjs';
const dir = mkdtempSync(join(tmpdir(), 'push-complete-')); const env = { DAILY_BRIEF_DB: join(dir, 'brief.sqlite'), MINIMAX_API_KEY: 'fixture-only' };
const market = openMarketAlertsStore(join(dir, 'market.sqlite')); const pushStore = openWebPushStore(join(dir, 'push.sqlite'));
const ec = createECDH('prime256v1'); ec.generateKeys();
const initial = pushNowMs - 300000;
try {
 market.commitOpportunityScan({ states: [], pushObservations: [], scannedAt: new Date(initial).toISOString() });
 pushStore.enrollDevice({ subscription: { endpoint: 'https://fcm.googleapis.com/integration', keys: { p256dh: ec.getPublicKey().toString('base64url'), auth: randomBytes(16).toString('base64url') } }, device: { deviceId: randomUUID(), deviceKey: randomBytes(32).toString('base64url') }, baseline: { sources: { market: 0, news: 0 }, marketEpisodes: [], enabledAt: new Date(initial).toISOString() }, nowMs: initial });
 const old = pushNowMs - 180000, oldAt = new Date(old).toISOString();
 const oldEvidence = structuredClone(opportunityDecision().metrics.pushEvidence);
 oldEvidence.sourceTimes = Object.fromEntries(Object.keys(oldEvidence.sourceTimes).map(key => [key, oldAt]));
 oldEvidence.candles = oldEvidence.candles.map(window => ({ ...window, openAt: oldAt, closeAt: new Date(old + window.intervalMs - 1).toISOString() }));
 const expired = qualifyOpportunity({ decision: opportunityDecision({ symbol: 'EXPIREDUSDT', observedAt: oldAt, pushEvidence: oldEvidence }), enrichment: { fetchedAt: oldAt, stale: false, error: null }, scanId: 'old' }, old);
 assert.equal(expired.classification, 'qualified', 'expired delivery was genuinely valid when the producer first observed it');
 market.commitOpportunityScan({ states: [], pushObservations: [expired], scannedAt: oldAt });
 const observations = Array.from({ length: 8 }, (_, i) => qualifyOpportunity({ decision: opportunityDecision({ symbol: `VALID${i}USDT` }), enrichment: { fetchedAt: pushNow, stale: false, error: null }, scanId: 'current' }, pushNowMs));
 const ordinary = qualifyOpportunity({ decision: opportunityDecision({ symbol: 'ORDINARYUSDT' }, { confidence: 79 }), enrichment: { fetchedAt: pushNow, stale: false, error: null }, scanId: 'ordinary' }, pushNowMs);
 market.commitOpportunityScan({ states: [], pushObservations: [...observations, ordinary], scannedAt: pushNow });
 market.commitOpportunityScan({ states: [], pushObservations: observations, scannedAt: pushNow });
 const assessment = { exceptional: true, category: '已公布的重大政策决定', fact: '正式公布重大政策决定', impact: '显著改变市场资金成本', candidateIndexes: [1] };
 const candidate = { id: 'https://www.reuters.com/world/integration', source: 'Reuters', title: '重大正式政策', summary: assessment.fact, url: 'https://www.reuters.com/world/integration', publishedAt: pushNow, publicationTimeBasis: 'publication', imageUrl: null, language: 'English', country: 'US' };
 const item = { rank: 1, importance: 'high', title: candidate.title, topic: '宏观 / 地缘政治 / 原油', candidateIndexes: [1], sourceNames: ['Reuters'], sourceUrls: [candidate.url], imageUrl: null, whatHappened: assessment.fact, investmentImpact: assessment.impact, watchNext: '实施', pushAssessment: assessment };
 const generate = async request => ({ brief: { title: '简报', marketPulse: '', items: [item, { ...item, title: '普通新闻', importance: 'medium', pushAssessment: { ...assessment, exceptional: false } }], watchVariables: [], priorityLine: '' }, provider: request.provider });
 await getOrCreateDailyInvestmentBrief({ now: new Date(pushNowMs), env, collectCandidates: async () => [candidate], requestBrief: generate });
 assert.equal(readDailyBriefPushOutboxAfter(0, 100, env).length, 1);
 const sent = [], sender = { send: async (_, event) => { sent.push(event); return { kind: 'accepted', statusCode: 201, retryAfterMs: null, errorCode: null }; } };
 const input = { pushStore, marketSource: createMarketPushSource(market), newsSource: createNewsPushSource(env), sender, owner: 'integration' };
 await runWebPushCycle({ ...input, nowMs: pushNowMs, now: () => pushNowMs });
 for (const offset of [5000, 10000, 15000]) await runWebPushCycle({ ...input, nowMs: pushNowMs + offset, now: () => pushNowMs + offset });
 assert.equal(sent.filter(event => event.source === 'market').length, 8);
 assert.equal(sent.filter(event => event.source === 'news').length, 1);
 assert.equal(new Set(sent.map(event => event.id)).size, 9);
 assert.equal(sent.some(event => event.title.includes('ORDINARY') || event.title.includes('EXPIRED')), false);
 assert.ok(pushStore.readDeliveryCounts().expired >= 1);
} finally { market.close(); pushStore.close(); rmSync(dir, { recursive: true, force: true }); }
console.log('real producers to persistent fanout and prioritized sender integration passed');
