import assert from 'node:assert/strict';
import { createECDH, randomBytes, randomUUID } from 'node:crypto';
import { openWebPushStore } from './web-push-store.ts';
import { createAdminSessionToken } from './admin-auth.ts';
import { createWebPushApiHandlers, revokePushForLogout } from './web-push-api.ts';
const nowMs = Date.parse('2026-10-02T02:00:00Z');
const ec = createECDH('prime256v1'); ec.generateKeys();
const env = { ADMIN_PASSWORD: 'test-password', ADMIN_SESSION_SECRET: randomBytes(32).toString('hex'), WEB_PUSH_ENABLED: 'true', WEB_PUSH_VAPID_PUBLIC_KEY: ec.getPublicKey().toString('base64url'), WEB_PUSH_VAPID_PRIVATE_KEY: ec.getPrivateKey().toString('base64url'), WEB_PUSH_VAPID_SUBJECT: 'mailto:ops@example.com', SIGNAL_HUB_PUBLIC_ORIGIN: 'https://hub.example.com' };
const cookie = `signal_hub_admin=${createAdminSessionToken(env, nowMs)}`;
const store = openWebPushStore(':memory:');
const deviceId = randomUUID(), deviceKey = randomBytes(32).toString('base64url');
const subscription = { endpoint: 'https://fcm.googleapis.com/a', expirationTime: null, keys: { p256dh: env.WEB_PUSH_VAPID_PUBLIC_KEY, auth: randomBytes(16).toString('base64url') } };
const baseline = { sources: { market: 7, news: 3 }, marketEpisodes: [], enabledAt: new Date(nowMs).toISOString() };
let accepted = false;
const handlers = createWebPushApiHandlers({ store, sender: { send: async () => ({ kind: accepted ? 'accepted' : 'retry', errorCode: 'safe_failure' }) }, baselineProvider: () => baseline, env, now: () => nowMs });
const request = (method, body, headers = {}) => new Request('https://hub.example.com/api/push/subscriptions', { method, headers: { cookie, origin: 'https://hub.example.com', 'content-type': 'application/json', 'X-Signal-Push-Device': deviceId, 'X-Signal-Push-Device-Key': deviceKey, ...headers }, ...(body == null ? {} : { body: typeof body === 'string' ? body : JSON.stringify(body) }) });
try {
 assert.equal((await handlers.subscribe(request('POST', {}, { cookie: '' }))).status, 401);
 assert.equal((await handlers.subscribe(request('POST', {}, { origin: 'https://evil.test', 'x-forwarded-host': 'evil.test' }))).status, 403);
 assert.equal((await handlers.subscribe(request('POST', 'x'.repeat(9000)))).status, 413);
 assert.equal((await handlers.subscribe(request('POST', { deviceId, deviceKey, subscription: { ...subscription, endpoint: 'https://evil.test' } }))).status, 400);
 const response = await handlers.subscribe(request('POST', { deviceId, deviceKey, subscription }));
 assert.equal(response.status, 200); assert.equal((await response.json()).epoch, 1);
 assert.equal((await (await handlers.subscribe(request('POST', { deviceId, deviceKey, subscription }))).json()).epoch, 1);
 const config = await handlers.config(request('GET'));
 assert.equal(config.headers.get('cache-control'), 'private, no-store');
 assert.equal(JSON.stringify(await config.json()).includes(env.WEB_PUSH_VAPID_PRIVATE_KEY), false);
 assert.equal((await handlers.unsubscribe(request('DELETE', null, { 'X-Signal-Push-Device-Key': 'wrong' }))).status, 403);
 assert.equal((await handlers.testPush(request('POST'))).status, 502); accepted = true;
 assert.equal((await handlers.testPush(request('POST'))).status, 200);
 let resolveTest;
 const concurrent = createWebPushApiHandlers({ store, sender: { send: async () => new Promise(resolve => { resolveTest = resolve; }) }, baselineProvider: () => baseline, env, now: () => nowMs });
 const pendingTest = concurrent.testPush(request('POST'));
 await new Promise(resolve => setTimeout(resolve, 0));
 const rotated = { ...subscription, endpoint: 'https://fcm.googleapis.com/rotated' };
 store.enrollDevice({ device: { deviceId, deviceKey }, subscription: rotated, baseline, nowMs });
 resolveTest({ kind: 'gone', errorCode: 'push_gone' }); await pendingTest;
 assert.equal(store.getDeviceStatus(deviceId, deviceKey).enabled, true, 'late gone response must not revoke a newer epoch');
 assert.equal(store.readSourceCursor('market'), 0);
 const expiredCookie = `signal_hub_admin=${createAdminSessionToken(env, nowMs - 31 * 86400000)}`;
 assert.equal((await handlers.getSubscriptionStatus(request('GET', null, { cookie: expiredCookie }))).status, 401);
 assert.equal(store.getDeviceStatus(deviceId, deviceKey).enabled, true, 'natural session expiry keeps background enrollment');
 const localLogout = new Request('http://localhost:3107/api/logout', { method: 'POST', headers: { cookie, host: '127.0.0.1:3107', origin: 'http://127.0.0.1:3107', 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ pushDeviceId: deviceId, pushDeviceKey: deviceKey }) });
 assert.equal(await revokePushForLogout(localLogout, { env: { ...env, WEB_PUSH_ENABLED: 'false', SIGNAL_HUB_PUBLIC_ORIGIN: undefined }, now: () => nowMs, store }), null, 'native Next hostname normalization must preserve same-origin local logout');
 store.enrollDevice({ subscription, device: { deviceId, deviceKey }, baseline, nowMs });
 const logout = new Request('https://hub.example.com/api/logout', { method: 'POST', headers: { cookie, origin: 'https://hub.example.com', 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ pushDeviceId: deviceId, pushDeviceKey: deviceKey }) });
 assert.equal(await revokePushForLogout(logout, { env, now: () => nowMs, store }), null);
 assert.equal(store.getDeviceStatus(deviceId, deviceKey).enabled, false);
} finally { store.close(); }
console.log('authenticated current-device push controls tests passed');
