import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { initXPipelineDb, upsertXPipelineRealtimeUpdate, setXPipelineHealth } from "./x-pipeline-store.ts";
import { getXAccountCoverageSnapshot, initXOwnedReaderStateDb, prepareXOwnedReaderAccounts, getXOwnedReaderAccountState } from "./x-owned-reader-state.ts";
import { getXOwnedReaderConfig } from "./x-owned-reader-config.ts";

const db = new DatabaseSync(":memory:");
initXPipelineDb(db);
const now = Date.parse("2026-10-04T02:00:00Z");
const env = { X_OWNED_READER_ENABLED: "true", X_OWNED_READER_SESSION_DB: "/secret/session.db", X_OWNED_READER_COOLDOWN_FILE: "/secret/cooldown.json", TWITTER_TOKEN: "secret-token" };
const beforeTables = db.prepare("select name from sqlite_master where type='table'").all();
const first = getXAccountCoverageSnapshot(["Hzzzz666", "fffffiyes_yu", "Established985", "newAuthor"], db, env, now);
assert.deepEqual(db.prepare("select name from sqlite_master where type='table'").all(), beforeTables, "read-only coverage must not initialize state tables");
assert.equal(first.accounts[0].route, "owned-reader");
assert.equal(first.accounts[0].evidence, "unverified");
assert.equal(first.accounts[1].evidence, "unmonitored");
assert.equal(first.accounts[2].route, "monitor985");
assert.equal(first.accounts[3].evidence, "unverified");
assert.equal(first.counts.total, 4);
assert.equal(first.counts.ownedReader, 2);
assert.equal(JSON.stringify(first).includes("secret"), false);
initXOwnedReaderStateDb(db);
const config = getXOwnedReaderConfig(env);
assert.deepEqual(prepareXOwnedReaderAccounts(["Hzzzz666"], config, db, now), [{ username: "hzzzz666", fromAt: "2026-10-02T02:00:00.000Z", throughAt: "2026-10-04T02:00:00.000Z" }]);
assert.deepEqual(prepareXOwnedReaderAccounts(["Hzzzz666"], config, db, now + 300000), [{ username: "hzzzz666", fromAt: "2026-10-02T02:00:00.000Z", throughAt: "2026-10-04T02:00:00.000Z" }]);
assert.equal(getXOwnedReaderAccountState("Hzzzz666", db).bootstrapFromAt, "2026-10-02T02:00:00.000Z");
db.prepare("update x_owned_reader_state set covered_through_at=?, pending_through_at=null,last_successful_check_at=?,status='complete' where username_key=?").run("2026-10-04T02:00:00.000Z", "2026-10-04T02:01:00.000Z", "hzzzz666");
assert.deepEqual(prepareXOwnedReaderAccounts(["hzzzz666"], config, db, now + 600000), [{ username: "hzzzz666", fromAt: "2026-10-04T01:45:00.000Z", throughAt: "2026-10-04T02:10:00.000Z" }]);
setXPipelineHealth({scope:"collector",status:"live",detail:"other worker"},db);
const stale = getXAccountCoverageSnapshot(["hzzzz666"],db,env,now+1200000);
assert.equal(stale.accounts[0].stale,true);
assert.equal(stale.counts.stale,1);
db.prepare("update x_owned_reader_state set last_successful_check_at='2099-01-01T00:00:00Z' where username_key='hzzzz666'").run();
assert.equal(getXAccountCoverageSnapshot(["hzzzz666"],db,env,now).accounts[0].reason,"invalid_check_timestamp");
upsertXPipelineRealtimeUpdate({eventType:"NEW_TWEET",account:"Established985",displayName:"Established985",createdAt:"2026-10-04T00:00:00Z",profileUrl:"https://x.com/Established985",remark:"",feedItem:{id:"1234567890123456789",username:"Established985",displayName:"Established985",text:"prior source observation",createdAt:"2026-10-04T00:00:00Z",profileUrl:"https://x.com/Established985",userAvatar:"",tweetUrl:"https://x.com/Established985/status/1234567890123456789",hashtags:[],likes:0,retweets:0,replies:0,quotes:0,views:0,media:[],quotedTweet:null,origin:"watch",queryLabel:"985monitor",translation:null}},db);
assert.equal(getXAccountCoverageSnapshot(["Established985"],db,env,now).accounts[0].evidence,"covered");
db.prepare("insert into x_owned_reader_control(id,paused,reason,next_retry_at,updated_at) values(1,1,'rate_limited','malformed',?)").run("2026-10-04T02:00:00Z");
assert.equal(getXAccountCoverageSnapshot(["photoncap"],db,env,now).accounts[0].status,"paused","an invalid persisted cooldown must not silently resume requests");
db.close();
console.log("Owned state: read-only coverage, fixed bootstrap/retry, overlap, independent stale health and source evidence passed.");
