import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(
  new URL("./alpha-research-page.tsx", import.meta.url),
  "utf8",
);

assert.match(source, /<section className="[^"]*lg:sticky[^"]*"/);
assert.match(source, /<section className="[^"]*lg:top-\[5\.25rem\][^"]*"/);
assert.match(source, /<section className="[^"]*lg:z-30[^"]*"/);
assert.match(source, /<section className="[^"]*lg:backdrop-blur-xl[^"]*"/);
assert.match(source, /StocksResearchLayout/);
assert.match(source, /StocksSubscriptionReports/);
assert.match(source, /StocksHynixPremiumCurve/);
assert.match(source, /<StocksHynixPremiumCurve \/>/);
assert.match(source, /buildStocksSubscriptionReports\(stocks\)/);
assert.match(source, /stocksDataHealthItems/);
assert.match(source, /数据健康中心/);
assert.match(source, /行情/);
assert.match(source, /财报/);
assert.match(source, /新闻/);
assert.match(source, /type AlphaTab = "research" \| "reports" \| "messages"/);
assert.match(source, /行情\/财报\/新闻优先，TG\/X 补充信号/);
assert.match(source, /订阅研报/);
assert.match(source, /setActiveTab\("research"\)/);
assert.match(source, /\/api\/stocks-performance\?tickers=/);
assert.match(source, /startDate=/);
assert.match(source, /performanceTickersKey/);
assert.match(source, /activeSectorId=\{selectedSector\?\.id/);
assert.match(source, /onSelectSector=\{\(sectorId\) =>/);
assert.match(source, /setSelectedTicker\(sector\.tickers\[0\]\)/);
assert.match(source, /STOCKS_MARKET_SNAPSHOT_CACHE_KEY/);
assert.match(source, /useBrowserJsonCache/);
assert.doesNotMatch(source, /useEffect\(\(\) => \{[\s\S]*?setMarketSnapshot\(/);
assert.doesNotMatch(source, /useEffect\(\(\) => \{[\s\S]*?setFinancialSnapshot\(/);
assert.doesNotMatch(source, /useEffect\(\(\) => \{[\s\S]*?setCatalystSnapshot\(/);
assert.doesNotMatch(source, /window\.localStorage\.getItem/);
assert.doesNotMatch(source, /window\.localStorage\.setItem/);
assert.match(source, /useState<StocksMarketSnapshot \| null>\(null\)/);
assert.match(source, /useState<StocksFinancialSnapshot \| null>\(null\)/);
assert.match(source, /useState<StocksCatalystSnapshot \| null>\(null\)/);
assert.match(source, /useState<KeyedPerformanceSnapshot \| null>\(null\)/);
assert.doesNotMatch(source, /useState<StocksMarketSnapshot \| null>\(\(\) =>/);
assert.doesNotMatch(source, /useState<StocksFinancialSnapshot \| null>\(\(\) =>/);
assert.doesNotMatch(source, /useState<StocksCatalystSnapshot \| null>\(\(\) =>/);
assert.doesNotMatch(source, /useState<StocksPerformanceSnapshot \| null>\(\(\) =>/);
assert.doesNotMatch(source, /readCachedSnapshot/);
assert.doesNotMatch(source, /writeCachedSnapshot/);
assert.match(source, /useBrowserJsonCache<StocksMarketSnapshot>\(STOCKS_MARKET_SNAPSHOT_CACHE_KEY\)/);
assert.match(source, /writeMarketSnapshotCache\(snapshot\)/);
assert.match(source, /useBrowserJsonCache<StocksFinancialSnapshot>/);
assert.match(source, /writeFinancialSnapshotCache\(snapshot\)/);
assert.match(source, /useBrowserJsonCache<StocksCatalystSnapshot>/);
assert.match(source, /writeCatalystSnapshotCache\(snapshot\)/);
assert.match(source, /performanceSnapshotCacheKey\(performanceTickersKey\)/);
assert.match(source, /useBrowserJsonCache<StocksPerformanceSnapshot>\(performanceCacheKey\)/);
assert.match(source, /setLivePerformanceSnapshot\(\{ cacheKey, snapshot \}\)/);
assert.match(source, /writePerformanceSnapshotCache\(snapshot\)/);
assert.match(source, /livePerformanceSnapshot\?\.cacheKey === performanceCacheKey/);
assert.match(source, /hasPerformanceSeries\(snapshot\)/);
assert.match(source, /hasPerformanceSeries\(cachedPerformanceSnapshot\)/);
assert.match(source, /if \(hasPerformanceSeries\(snapshot\)\)/);
assert.match(source, /snapshotIssueLabel/);
assert.match(source, /refresh failed; using cached snapshot/);
assert.match(source, /刷新失败，使用缓存/);
assert.match(source, /isPerformanceCacheNotice/);
assert.match(source, /performanceIssueLabel/);
assert.match(source, /使用最近缓存/);
assert.match(source, /snapshotStatusTitle/);
assert.match(source, /snapshot\.source === "mock"/);
assert.doesNotMatch(source, /部分源失败/);
assert.match(source, /已回落本地/);
assert.match(source, /setFinancialError\(null\)/);
assert.match(source, /setCatalystError\(null\)/);
assert.match(source, /\/api\/stocks-research-state/);
assert.match(source, /method:\s*"PUT"/);
assert.match(source, /researchStates/);

console.log("ok - alpha research page sticky controls");
